# Generated by Django 5.0.4 on 2024-04-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.CharField(max_length=100),
        ),
    ]
