# Generated by Django 5.0.4 on 2024-04-26 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_alter_users_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="email",
            new_name="username",
        ),
    ]
