# Generated by Django 5.0.4 on 2024-04-26 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0003_rename_email_users_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="username",
            new_name="email",
        ),
    ]
