# Generated by Django 5.0.4 on 2024-04-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0004_rename_username_users_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("passkey", models.CharField(max_length=100)),
            ],
        ),
    ]
