# Generated by Django 5.0.4 on 2024-04-27 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0005_admins"),
    ]

    operations = [
        migrations.CreateModel(
            name="PID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PID", models.CharField(max_length=10)),
                ("Student_Name", models.CharField(max_length=30)),
                ("Student_RollNo", models.CharField(max_length=15)),
                ("Project_Name", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Admins",
        ),
        migrations.CreateModel(
            name="Marks",
            fields=[
                (
                    "pid_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="login.pid",
                    ),
                ),
                ("Initial_submission", models.IntegerField()),
                ("Final_submission", models.IntegerField()),
                ("Plagiarism", models.IntegerField()),
            ],
            bases=("login.pid",),
        ),
    ]
