# Generated by Django 5.0.4 on 2024-04-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0006_pid_delete_admins_marks"),
    ]

    operations = [
        migrations.CreateModel(
            name="team_admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name="Users",
            new_name="reviewer",
        ),
    ]
