# Generated by Django 5.0.4 on 2024-04-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0007_team_admin_rename_users_reviewer"),
    ]

    operations = [
        migrations.AddField(
            model_name="marks",
            name="Reviewer_Mark",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="marks",
            name="Team_communication_mark",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="marks",
            name="Worklog",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="marks",
            name="Final_submission",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="marks",
            name="Initial_submission",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="marks",
            name="Plagiarism",
            field=models.IntegerField(default=0),
        ),
    ]
