# Generated by Django 5.0.4 on 2024-12-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0008_marks_reviewer_mark_marks_team_communication_mark_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewer",
            name="password",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
