# Generated by Django 5.0.4 on 2024-12-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0009_alter_reviewer_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewer",
            name="reviewer_name",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="team_admin",
            name="admin_name",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
