# Generated by Django 5.0.4 on 2025-01-07 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0011_alter_marks_final_submission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marks",
            name="Total",
            field=models.FloatField(
                default=-1,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
