# Generated by Django 5.0.4 on 2025-01-07 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0012_marks_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marks",
            name="Total",
            field=models.FloatField(
                default=-1,
                validators=[
                    django.core.validators.MinValueValidator(-1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
